name: Constructorator
favicon: null
layout_spectrum: 0.23858
typography_spectrum: 0.49008
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0e0d'
    - '#d8d5cc'
    - '#9a988b'
    - '#4f504b'
    - '#1b75aa'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
