name: Constructorator
favicon: null
layout_spectrum: 0.5969932158477604
typography_spectrum: 0.7064669290557504
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0e0d'
    - '#d8d5cc'
    - '#9a988b'
    - '#4f504b'
    - '#1b75aa'
  brandStrength: 0.4319962824229151
  lightness: 0.9790794404689223
  saturation: 0.5741196982562542
  rhythmicContrast: 1
purpose: []
