typography_spectrum: 0.49008
color:
  brandColors:
    - '#0c0e0d'
    - '#d8d5cc'
    - '#9a988b'
    - '#4f504b'
    - '#1b75aa'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.23858
analytics:
  google: null
  facebook: null
  twitter: null
name: Constructorator
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    url: 'http://www.constructorator.com/about.html'
    type: external
favicon: null
purpose: []
